my_file = open('dz52.txt', 'r')
content = my_file.read()
print(f'Содержимое файла: \n {content}')
my_file = open('dz52.txt', 'r')
content = my_file.readlines()
print(f'Количество строк в файле - {len(content)}')
my_file = open('dz52.txt', 'r')
content = my_file.readlines()
for i in range(len(content)):
    print(f'Окличество символов в {i + 1} строке - {len(content[i])}')
my_file = open('dz52.txt', 'r')
content = my_file.read()
content = content.split()
print(f'Общее количество слов - {len(content)}')
my_file.close()
